### ISSUE TITLE
Request addition of license in order to raise pull request

### ISSUE THREAD

**Issue by Farmadupe** [HULKs/cgos-rs#1]
I have drafted an integration for the CGOS `I2C` functions and would like to raise a PR. In order for me to do this, the project would require a license. 

Request addition of any suitable license for this purpose. For reference, Congatec licenses libcgos under BSD 2-clause. This would be my preferred choice

**Comment by schmidma** [comment]
Thanks for raising this issue, your PR is very welcome :heart: 

I added a license in https://github.com/HULKs/cgos-rs/commit/ca9c5f32c75482fdb8c3c2b0079bce2d4d65ec6d
